### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by r3nya** [yarikpwnzer/react-native-survey-monkey#1]
Hi @yarikpwnzer,

Thanks for your job!

[You mentioned](https://github.com/yarikpwnzer/react-native-survey-monkey/blob/master/README.md#android) that you will add Android support later. 
Do you have time for it? If yes, do you have any ideas about ETA? :)

Thanks in advance.

**Comment by yarikpwnzer** [comment]
@r3nya added few seconds ago, but we need to test it today, so stable version will be today EoD.

**Comment by r3nya** [comment]
Cool! I can test it next week as well. ;)

**Comment by yarikpwnzer** [comment]
@r3nya No problems, feel free to open issues if You will find something ;)

**Comment by r3nya** [comment]
Got it, thank you!
