### ISSUE TITLE
No file chosen

### ISSUE THREAD

**Issue by lguardado** [yarikpwnzer/react-native-survey-monkey#15]
iOS 14.5
"react-native": "0.62.2"
After selecting "choose file" to upload to survey monkey and chosing an image from library the survey show "no file chosen". Apparently the survey gets refreshed after the user selects an image.

The survey hash is `QH5SGXQ`
Any idea if this is in the library's scope?

Another issue is that the app crashes when trying to pick it from the camera.

Note: These two options work ok if using safari instead of the app with the APK

**Comment by yarikpwnzer** [comment]
@lguardado Hello. I think this functionality is not implemented by survey-monkey developers. What I found on web https://stackoverflow.com/questions/41880329/how-do-you-get-the-surveymonkey-sdk-to-upload-images-on-ios-and-android . If you have time, You can check if it will work with native iOS SDK.

**Comment by lguardado** [comment]
@yarikpwnzer thank you so much for the quick reply... ouch! I'll try to find a workaround then. 
Thanks again!

I'll close this issue then!

**Comment by lguardado** [comment]
@yarikpwnzer just a question... 
I saw in the link you shared that the issue is related to iOSUIWebviews, but if I use `react-native-webview` I'm able to pick photos with no issue.... does this makes sense? I assume that library uses the same iOS webview

**Comment by yarikpwnzer** [comment]
@lguardado I think web view question should be addressed to survey monkey devs. I just made bridge library for react with all functionality that native iOS library has. Same with prefixes, if they are not available in native SDK they won't be available in react-native bridge library.

**Comment by lguardado** [comment]
Yes, fair enough... I was wondering if you were using the same webview than them. I've addressed a ticket to survey monkey's support and they can't help.

Thanks anyways for the help, I appreciate it!

**Comment by yarikpwnzer** [comment]
@lguardado yeah they are not very responsible guys. They don't want to help and also they rejected me free key for mobile testing on react-native:
<img width="1272" alt="Знімок екрана 2021-05-22 о 00 29 48" src="https://user-images.githubusercontent.com/5438263/119200059-dcf67e80-ba94-11eb-8bbc-157a69b14620.png">
