### ISSUE TITLE
IOS App crashing on selecting "Yes" from the 2 options ("Yes","No") in a survey

### ISSUE THREAD

**Issue by punittttt** [yarikpwnzer/react-native-survey-monkey#16]
Hi @yarikpwnzer 
Survey monkey works great in both the platform, ios and android.
But since last 2 days i have been facing an issue with IOS only regarding one survey.

The survey contains 6 covid questions with 2 answers as an option given to the user to select from...its either "Yes" or "No".
if the user selects "No" for each question, it works as expected(I get all the data in JSON and get to play with it the details) but if the user selects "yes" for any answer, it throws me this error

**Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndexedSubscript:]: index 9223372036854775807 beyond bounds [0 .. 1]'**

I am not able to get my head around this issue. Can you confirm if it is a bug in survey monkey library or i am handling it in a wrong way.
Any help would be appreciated.

Thanks,
Punit

**Comment by yarikpwnzer** [comment]
Hi @punittttt please give me a survey hash, so I can check.

**Comment by punittttt** [comment]
Hi @yarikpwnzer Thanks for replying.
Here is the hash key **LR7RNHW**

**Comment by punittttt** [comment]
@yarikpwnzer , do not bother looking into it..i had selected "disqualification page" property on the yes button thats why it was crashing.
I get to fixed it when after clearing it.

Thanks for your help.
Punit
