### ISSUE TITLE
Android App crashes on SurveyMonkey screen 

### ISSUE THREAD

**Issue by adrianobragaalencar** [yarikpwnzer/react-native-survey-monkey#19]
Hi @yarikpwnzer

Our Android app is crashing whenever we open the surveymonkey screen, goes to background and clicks again on the app icon instead of recent apps menu to bring back the app to foreground.

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.content.Intent.getSerializableExtra(java.lang.String)' on a null object reference
       at com.surveymonkey.RNSurveyMonkeyModule$2.onActivityResult(RNSurveyMonkeyModule.java:176)
       at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:305)
       at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:762)
       at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
       at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
       at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)

The app screen is pretty simple as below:

`const onPress = useCallback(() => {
    if (surveyMonkeyRef.current) {
      surveyMonkeyRef.current.showSurveyMonkey(hash, null);
    }
  }, [hash]);
`

`<TouchableNativeFeedback onPress={onPress}>
      <View style={styles.feedbackListItemContainer}>
        <SurveyMonkey
          ref={surveyMonkeyRef}
          cancelButtonTintColor="blue"/>
`

Any help would be appreciated.

Thanks,
Adriano Braga

**Comment by yarikpwnzer** [comment]
@adrianobragaalencar hi, we will check it later today.

**Comment by adrianobragaalencar** [comment]
Thank you, @yarikpwnzer we've fixed on our side using patch package. Please refer the code below if it helps somehow.

`
diff --git a/node_modules/react-native-survey-monkey/android/src/main/java/com/surveymonkey/RNSurveyMonkeyModule.java b/node_modules/react-native-survey-monkey/android/src/main/java/com/surveymonkey/RNSurveyMonkeyModule.java
index c4a3796..44f1530 100644
--- a/node_modules/react-native-survey-monkey/android/src/main/java/com/surveymonkey/RNSurveyMonkeyModule.java
+++ b/node_modules/react-native-survey-monkey/android/src/main/java/com/surveymonkey/RNSurveyMonkeyModule.java
@@ -166,7 +166,7 @@ public class RNSurveyMonkeyModule extends ReactContextBaseJavaModule {
     private final ActivityEventListener activityEventListener = new ActivityEventListener() {
         @Override
         public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
-            if (requestCode != REQUEST_CODE)
+            if (requestCode != REQUEST_CODE || resultCode == Activity.RESULT_CANCELED)
                 return;
 
             if (resultCode == Activity.RESULT_OK) {

`

**Comment by yarikpwnzer** [comment]
@adrianobragaalencar sorry for delay (we have a lot of work on our main job), our Android developer will check it soon.

**Comment by yarikpwnzer** [comment]
@adrianobragaalencar we used Your fix, crash gone. Version bumped to 1.2.5. Please update library.

**Comment by adrianobragaalencar** [comment]
Thank you guys, I'm going to move our code for your fix.
