### ISSUE TITLE
IOS issue

### ISSUE THREAD

**Issue by darialu** [yarikpwnzer/react-native-survey-monkey#4]
Hi @yarikpwnzer 
I've experienced a bug on iOS. When user tries to open survey and press "Cancel" in web view instead of completing a survey for few times (2 or more) - survey web view is not showed anymore. If user kills and open app again or if just wait for 1-2 min and try to open survey - survey web view will be represented. Happens only on iOS, react-native version is 0.59.10. After debugging it seems like react native bug. It will be nice if you have any thoughts about how it can be fixed .Thanks

**Comment by yarikpwnzer** [comment]
@darialu hi I will check it later today.

**Comment by yarikpwnzer** [comment]
@darialu I checked on 0.62 RN, seems no issues with 'Cancel' and open again. Check Your code or try to upgrade RN to latest one.
First time it takes some time to load, seems some delay from survey-monkey sdk, but not 1-2 min (max 3 seconds) - You can preload it and hide until user will click somewhere in Your flow, to complete survey, also You can show some HUD animation before web view will appear.

https://gph.is/g/EGdnxbM

**Comment by yarikpwnzer** [comment]
@darialu we started this lib on 0.59 RN it worked same as on gif, so possible issue inside your component.

**Comment by darialu** [comment]
@yarikpwnzer will try to upgrade RN, thank you!
