### ISSUE TITLE
Crashes when offline 

### ISSUE THREAD

**Issue by bensinjin** [yarikpwnzer/react-native-survey-monkey#5]
I was testing this on the iOS simulator and noticed if I turn off my wifi then press the link to open the survey the app crashes. I guess I can make sure we don't show the link if we're offline but is this expected behaviour?

**Comment by yarikpwnzer** [comment]
@bensinjin its issue, I will try to fix it today or tomorrow.

**Comment by yarikpwnzer** [comment]
@bensinjin fixed in new release (version 1.2.1). Please update library.

**Comment by bensinjin** [comment]
Great thanks!

**Comment by yarikpwnzer** [comment]
@bensinjin You are welcome! I’m closing this issue than.
