### ISSUE TITLE
Android React-native bridging issue using native module

### ISSUE THREAD

**Issue by punittttt** [yarikpwnzer/react-native-survey-monkey#9]
Hi @yarikpwnzer @rMozes.
Great job with the survey - monkey react-native library.
Although when i tried to integrate it with my react-native project i came up with issues on both the platforms.

ANDROID:
First i will discuss the issue i am facing in android.
When i bridge the react-native with android native part , using NativeModules.RNSurveyMonkey.presentSurveyMonkey , i can see that the public void **presentSurveyMonkey(final String surveyHash,
                                    final ReadableMap customVariables,
                                    final String scheduleInterceptTitle,
                                    final ReadableMap scheduleInterceptParams)** method is not getting called in RNSurveyMonkeyModule.java. I am doing exactly as mentioned in the documentation. Please have a look into that issue.

IOS:
Talking of IOS, i am using Macbook Pro and when i tried giving the path in the podfile, I am facing issues of what i am attaching screenshots

<img width="1436" alt="Screenshot 2021-01-29 at 15 01 16" src="https://user-images.githubusercontent.com/33680147/109534152-ecc47f00-7ab2-11eb-96bf-77f4b2976ddb.png">
<img width="1426" alt="Screenshot 2021-01-29 at 15 01 35" src="https://user-images.githubusercontent.com/33680147/109534165-f1893300-7ab2-11eb-8362-a20c3e0c9a82.png">
<img width="679" alt="Screenshot 2021-01-29 at 15 03 56" src="https://user-images.githubusercontent.com/33680147/109534180-f51cba00-7ab2-11eb-8fa4-928dd9167997.png">

**Comment by yarikpwnzer** [comment]
Hi @punittttt try to install library without pods (option B) from documentation.

**Comment by punittttt** [comment]
Hey, thanks @yarikpwnzer , i got it all working. 
Thank you for the help

Closing this issue
